### ISSUE TITLE
DB 설계 및 모델 생성

### ISSUE THREAD

**Issue by jch422** [boostcamp-2020/IssueTracker-24#1]
## 🥇 목표
BE 개발환경을 세팅하고, ERD 를 바탕으로 DB를 설계한다.
## 😄 완료 조건
- [x] NCP에 MySQL 서버 세팅
- [x] ERD 작성
- [x] 모델 생성 (Sequelize)

## 🔥 레퍼런스
- Lucas

**Comment by qkrrlgh519** [comment]
test

**Comment by qkrrlgh519** [comment]
test

**Comment by qkrrlgh519** [comment]
:fire: 분류가 잘 된 것같습니다.
