### ISSUE TITLE
[#Epic 18] 레이블/마일스톤 탭을 이동할 수 있다

### ISSUE THREAD

**Issue by jch422** [boostcamp-2020/IssueTracker-24#101]
## 🥇  목표
- 레이블과 마일스톤 탭을 오갈 수 있다.

## 😄  완료 조건
- [x] 레이블 / 마일스톤 탭 ui 구현
- [x] 레이블 / 마일스톤 탭에 대한 이벤트 구현

### 🕺  UI
![image](https://user-images.githubusercontent.com/38288479/97833667-383f6a00-1d19-11eb-8715-9a9f6a05c44a.png)

## 🌲 브랜치
- feature-label-tab

### 🔥  레퍼런스
[기획서](https://docs.google.com/presentation/d/1iA-tpumHl_TpR_yUwgYcnb_X8GbW6XvjZOTh2Ucvu0A/preview?pru=AAABdYa_uas*Fuku9RAcUdMBG7REzgBhIg&slide=id.g8582887c3d_0_12)

**Comment by mu1616** [comment]
ㅇㄹㄴㅇㄹ
