### ISSUE TITLE
React children 사용에 대해서 질문 있습니다!

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/IssueTracker-24#23]
https://github.com/boostcamp-2020/IssueTracker-24/blob/e6f376038ee35e219bff1eed0cbfb4390189fe68/client/src/components/login/loginContainer/loginContainer.jsx#L5-L12

```
어떤 컴포넌트들은 어떤 자식 엘리먼트가 들어올 지 미리 예상할 수 없는 경우가 있습니다. 
범용적인 ‘박스’ 역할을 하는 Sidebar 혹은 Dialog와 같은 컴포넌트에서 특히 자주 볼 수 있습니다.
이러한 컴포넌트에서는 특수한 children prop을 사용하여 자식 엘리먼트를 출력에 그대로 전달하는 것이 좋습니다.
```

### ❓ Question
children을 언제 사용하는지에 대해서 찾아봤는데 어떤 자식 엘리먼트가 들어올 지 예상할 수 없는 경우, 
재사용성을 위해 사용한다고 합니다. 

저희 코드에서는 LoginContainer를 재사용할 일이 없기 때문에 아래 코드 처럼
명시적으로 어떤 컴포넌트가 들어올 지 작성하는게 더 좋다고 생각하는데 어떻게 생각하시나요??
```
const LoginContainer = ({ children }) => (
  <>
    <div className="login-block">
      <div className="login-title">이슈 트래커</div>
      <LoginFormContainer />
    </div>
  </>
);
```

### 📚 레퍼런스
https://blog.sonim1.com/186

**Comment by thdwlsgus0** [comment]
흠 그렇겠네요.. 그러면 LoginFormContainer를import해주고, children을 객체로 보내줄 필요가 없겠네요 ㅎㅎ
